<div id="news">
	<ul class="newsticker">
		<li>GET GAMES FOR 10% THEIR STEAM PRICE RIGHT HERE! WE ACCEPT LATIUM!</li>
		<li>CONTACT US IF YOU WANT TO BUY AD SPACE!</li>
		<li>GET 5 FREE LATIUM BY CLICKING ON 'GET LATIUM' BUTTON</li>
		<li>NEW GAMES ADDED REGULARLY, CHECK BACK AGAIN LATER FOR NEW GAMES</li>
		<li>SPEND LATIUM ON LATIUMGAMES.CF! WE ALSO ACCEPT PAYPAL PAYMENTS</li>
	</ul>
</div>